/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *AccessPolicy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *IngressGateway) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *IngressGatewayRouteTable) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Mesh) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VirtualDeployment) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VirtualService) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VirtualServiceRouteTable) Hub() {}
