apiVersion: servicemesh.oci.upbound.io/v1alpha1
kind: VirtualServiceRouteTable
metadata:
  annotations:
    meta.upbound.io/example-id: servicemesh/v1alpha1/virtualserviceroutetable
  labels:
    testing.upbound.io/example-name: test_virtual_service_route_table
  name: test-virtual-service-route-table
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    definedTags:
      foo-namespace.bar-key: value
    description: ${var.virtual_service_route_table_description}
    freeformTags:
      bar-key: value
    name: ${var.virtual_service_route_table_name}
    priority: ${var.virtual_service_route_table_priority}
    routeRules:
    - destinations:
      - port: ${var.virtual_service_route_table_route_rules_destinations_port}
        virtualDeploymentIdSelector:
          matchLabels:
            testing.upbound.io/example-name: test_virtual_deployment
        weight: ${var.virtual_service_route_table_route_rules_destinations_weight}
      isGrpc: ${var.virtual_service_route_table_route_rules_is_grpc}
      path: ${var.virtual_service_route_table_route_rules_path}
      pathType: ${var.virtual_service_route_table_route_rules_path_type}
      requestTimeoutInMs: ${var.virtual_service_route_table_route_rules_request_timeout_in_ms}
      type: ${var.virtual_service_route_table_route_rules_type}
    virtualServiceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_virtual_service
