apiVersion: ons.oci.upbound.io/v1alpha1
kind: NotificationTopic
metadata:
  annotations:
    meta.upbound.io/example-id: ons/v1alpha1/notificationtopic
  labels:
    testing.upbound.io/example-name: test_notification_topic
  name: test-notification-topic
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    definedTags:
      Operations.CostCenter: "42"
    description: ${var.notification_topic_description}
    freeformTags:
      Department: Finance
    name: ${var.notification_topic_name}
