apiVersion: ons.oci.upbound.io/v1alpha1
kind: Subscription
metadata:
  annotations:
    meta.upbound.io/example-id: ons/v1alpha1/subscription
  labels:
    testing.upbound.io/example-name: test_subscription
  name: test-subscription
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    definedTags:
      Operations.CostCenter: "42"
    endpoint: ${var.subscription_endpoint}
    freeformTags:
      Department: Finance
    protocol: ${var.subscription_protocol}
    topicIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_notification_topic
